# coding: utf-8

"""
    Klarna Payments API V1

    The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from klarna_payments_python_sdk import schemas  # noqa: F401


class OrderLine(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "quantity",
            "total_amount",
            "name",
            "unit_price",
        }
        
        class properties:
            
            
            class name(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 1
            
            
            class quantity(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_minimum = 0
            
            
            class total_amount(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 200000000
            
            
            class unit_price(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 200000000
            
            
            class image_url(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 1024
                    min_length = 0
            
            
            class merchant_data(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 1024
                    min_length = 0
        
            @staticmethod
            def product_identifiers() -> typing.Type['ProductIdentifiers']:
                return ProductIdentifiers
            
            
            class product_url(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 1024
                    min_length = 0
            
            
            class quantity_unit(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 8
                    min_length = 1
            
            
            class reference(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    max_length = 255
                    min_length = 0
            
            
            class tax_rate(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_maximum = 10000
                    inclusive_minimum = 0
            
            
            class total_discount_amount(
                schemas.Int64Schema
            ):
            
            
                class MetaOapg:
                    format = 'int64'
                    inclusive_minimum = 0
            total_tax_amount = schemas.Int64Schema
            type = schemas.StrSchema
        
            @staticmethod
            def subscription() -> typing.Type['Subscription']:
                return Subscription
            __annotations__ = {
                "name": name,
                "quantity": quantity,
                "total_amount": total_amount,
                "unit_price": unit_price,
                "image_url": image_url,
                "merchant_data": merchant_data,
                "product_identifiers": product_identifiers,
                "product_url": product_url,
                "quantity_unit": quantity_unit,
                "reference": reference,
                "tax_rate": tax_rate,
                "total_discount_amount": total_discount_amount,
                "total_tax_amount": total_tax_amount,
                "type": type,
                "subscription": subscription,
            }
    
    quantity: MetaOapg.properties.quantity
    total_amount: MetaOapg.properties.total_amount
    name: MetaOapg.properties.name
    unit_price: MetaOapg.properties.unit_price
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_amount"]) -> MetaOapg.properties.total_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unit_price"]) -> MetaOapg.properties.unit_price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["image_url"]) -> MetaOapg.properties.image_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["merchant_data"]) -> MetaOapg.properties.merchant_data: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product_identifiers"]) -> 'ProductIdentifiers': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["product_url"]) -> MetaOapg.properties.product_url: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["quantity_unit"]) -> MetaOapg.properties.quantity_unit: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reference"]) -> MetaOapg.properties.reference: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tax_rate"]) -> MetaOapg.properties.tax_rate: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_discount_amount"]) -> MetaOapg.properties.total_discount_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["total_tax_amount"]) -> MetaOapg.properties.total_tax_amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subscription"]) -> 'Subscription': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "quantity", "total_amount", "unit_price", "image_url", "merchant_data", "product_identifiers", "product_url", "quantity_unit", "reference", "tax_rate", "total_discount_amount", "total_tax_amount", "type", "subscription", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity"]) -> MetaOapg.properties.quantity: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_amount"]) -> MetaOapg.properties.total_amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unit_price"]) -> MetaOapg.properties.unit_price: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["image_url"]) -> typing.Union[MetaOapg.properties.image_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["merchant_data"]) -> typing.Union[MetaOapg.properties.merchant_data, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product_identifiers"]) -> typing.Union['ProductIdentifiers', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["product_url"]) -> typing.Union[MetaOapg.properties.product_url, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["quantity_unit"]) -> typing.Union[MetaOapg.properties.quantity_unit, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reference"]) -> typing.Union[MetaOapg.properties.reference, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tax_rate"]) -> typing.Union[MetaOapg.properties.tax_rate, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_discount_amount"]) -> typing.Union[MetaOapg.properties.total_discount_amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["total_tax_amount"]) -> typing.Union[MetaOapg.properties.total_tax_amount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union[MetaOapg.properties.type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subscription"]) -> typing.Union['Subscription', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "quantity", "total_amount", "unit_price", "image_url", "merchant_data", "product_identifiers", "product_url", "quantity_unit", "reference", "tax_rate", "total_discount_amount", "total_tax_amount", "type", "subscription", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        quantity: typing.Union[MetaOapg.properties.quantity, decimal.Decimal, int, ],
        total_amount: typing.Union[MetaOapg.properties.total_amount, decimal.Decimal, int, ],
        name: typing.Union[MetaOapg.properties.name, str, ],
        unit_price: typing.Union[MetaOapg.properties.unit_price, decimal.Decimal, int, ],
        image_url: typing.Union[MetaOapg.properties.image_url, str, schemas.Unset] = schemas.unset,
        merchant_data: typing.Union[MetaOapg.properties.merchant_data, str, schemas.Unset] = schemas.unset,
        product_identifiers: typing.Union['ProductIdentifiers', schemas.Unset] = schemas.unset,
        product_url: typing.Union[MetaOapg.properties.product_url, str, schemas.Unset] = schemas.unset,
        quantity_unit: typing.Union[MetaOapg.properties.quantity_unit, str, schemas.Unset] = schemas.unset,
        reference: typing.Union[MetaOapg.properties.reference, str, schemas.Unset] = schemas.unset,
        tax_rate: typing.Union[MetaOapg.properties.tax_rate, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        total_discount_amount: typing.Union[MetaOapg.properties.total_discount_amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        total_tax_amount: typing.Union[MetaOapg.properties.total_tax_amount, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        type: typing.Union[MetaOapg.properties.type, str, schemas.Unset] = schemas.unset,
        subscription: typing.Union['Subscription', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OrderLine':
        return super().__new__(
            cls,
            *args,
            quantity=quantity,
            total_amount=total_amount,
            name=name,
            unit_price=unit_price,
            image_url=image_url,
            merchant_data=merchant_data,
            product_identifiers=product_identifiers,
            product_url=product_url,
            quantity_unit=quantity_unit,
            reference=reference,
            tax_rate=tax_rate,
            total_discount_amount=total_discount_amount,
            total_tax_amount=total_tax_amount,
            type=type,
            subscription=subscription,
            _configuration=_configuration,
            **kwargs,
        )

from klarna_payments_python_sdk.model.product_identifiers import ProductIdentifiers
from klarna_payments_python_sdk.model.subscription import Subscription
