# coding: utf-8

"""
    Klarna Payments API V1

    The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from klarna_payments_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from klarna_payments_python_sdk.api_response import AsyncGeneratorResponse
from klarna_payments_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from klarna_payments_python_sdk import schemas  # noqa: F401

from klarna_payments_python_sdk.model.error_v2 import ErrorV2 as ErrorV2Schema
from klarna_payments_python_sdk.model.customer import Customer as CustomerSchema
from klarna_payments_python_sdk.model.customer_token_creation_response import CustomerTokenCreationResponse as CustomerTokenCreationResponseSchema
from klarna_payments_python_sdk.model.customer_token_creation_request import CustomerTokenCreationRequest as CustomerTokenCreationRequestSchema
from klarna_payments_python_sdk.model.address import Address as AddressSchema

from klarna_payments_python_sdk.type.customer_token_creation_request import CustomerTokenCreationRequest
from klarna_payments_python_sdk.type.error_v2 import ErrorV2
from klarna_payments_python_sdk.type.address import Address
from klarna_payments_python_sdk.type.customer_token_creation_response import CustomerTokenCreationResponse
from klarna_payments_python_sdk.type.customer import Customer

from ...api_client import Dictionary
from klarna_payments_python_sdk.pydantic.address import Address as AddressPydantic
from klarna_payments_python_sdk.pydantic.error_v2 import ErrorV2 as ErrorV2Pydantic
from klarna_payments_python_sdk.pydantic.customer import Customer as CustomerPydantic
from klarna_payments_python_sdk.pydantic.customer_token_creation_response import CustomerTokenCreationResponse as CustomerTokenCreationResponsePydantic
from klarna_payments_python_sdk.pydantic.customer_token_creation_request import CustomerTokenCreationRequest as CustomerTokenCreationRequestPydantic

# Path params
AuthorizationTokenSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'authorizationToken': typing.Union[AuthorizationTokenSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_authorization_token = api_client.PathParameter(
    name="authorizationToken",
    style=api_client.ParameterStyle.SIMPLE,
    schema=AuthorizationTokenSchema,
    required=True,
)
# body param
SchemaForRequestBodyApplicationJson = CustomerTokenCreationRequestSchema


request_body_customer_token_creation_request = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
    },
)
SchemaFor200ResponseBodyApplicationJson = CustomerTokenCreationResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: CustomerTokenCreationResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: CustomerTokenCreationResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ErrorV2Schema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ErrorV2


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ErrorV2


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
)


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
)


@dataclass
class ApiResponseFor409(api_client.ApiResponse):
    body: schemas.Unset = schemas.unset


@dataclass
class ApiResponseFor409Async(api_client.AsyncApiResponse):
    body: schemas.Unset = schemas.unset


_response_for_409 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor409,
    response_cls_async=ApiResponseFor409Async,
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _generate_customer_token_mapped_args(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        _body = {}
        if description is not None:
            _body["description"] = description
        if billing_address is not None:
            _body["billing_address"] = billing_address
        if customer is not None:
            _body["customer"] = customer
        if intended_use is not None:
            _body["intended_use"] = intended_use
        if locale is not None:
            _body["locale"] = locale
        if purchase_country is not None:
            _body["purchase_country"] = purchase_country
        if purchase_currency is not None:
            _body["purchase_currency"] = purchase_currency
        args.body = _body
        if authorization_token is not None:
            _path_params["authorizationToken"] = authorization_token
        args.path = _path_params
        return args

    async def _agenerate_customer_token_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Generate a consumer token
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_authorization_token,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/payments/v1/authorizations/{authorizationToken}/customer-token',
            body=body,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_customer_token_creation_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _generate_customer_token_oapg(
        self,
        body: typing.Any = None,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Generate a consumer token
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_authorization_token,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/payments/v1/authorizations/{authorizationToken}/customer-token',
            body=body,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_customer_token_creation_request.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GenerateCustomerTokenRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def agenerate_customer_token(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._generate_customer_token_mapped_args(
            description=description,
            intended_use=intended_use,
            locale=locale,
            purchase_country=purchase_country,
            purchase_currency=purchase_currency,
            authorization_token=authorization_token,
            billing_address=billing_address,
            customer=customer,
        )
        return await self._agenerate_customer_token_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def generate_customer_token(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._generate_customer_token_mapped_args(
            description=description,
            intended_use=intended_use,
            locale=locale,
            purchase_country=purchase_country,
            purchase_currency=purchase_currency,
            authorization_token=authorization_token,
            billing_address=billing_address,
            customer=customer,
        )
        return self._generate_customer_token_oapg(
            body=args.body,
            path_params=args.path,
        )

class GenerateCustomerToken(BaseApi):

    async def agenerate_customer_token(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
        validate: bool = False,
        **kwargs,
    ) -> CustomerTokenCreationResponsePydantic:
        raw_response = await self.raw.agenerate_customer_token(
            description=description,
            intended_use=intended_use,
            locale=locale,
            purchase_country=purchase_country,
            purchase_currency=purchase_currency,
            authorization_token=authorization_token,
            billing_address=billing_address,
            customer=customer,
            **kwargs,
        )
        if validate:
            return CustomerTokenCreationResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(CustomerTokenCreationResponsePydantic, raw_response.body)
    
    
    def generate_customer_token(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
        validate: bool = False,
    ) -> CustomerTokenCreationResponsePydantic:
        raw_response = self.raw.generate_customer_token(
            description=description,
            intended_use=intended_use,
            locale=locale,
            purchase_country=purchase_country,
            purchase_currency=purchase_currency,
            authorization_token=authorization_token,
            billing_address=billing_address,
            customer=customer,
        )
        if validate:
            return CustomerTokenCreationResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(CustomerTokenCreationResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._generate_customer_token_mapped_args(
            description=description,
            intended_use=intended_use,
            locale=locale,
            purchase_country=purchase_country,
            purchase_currency=purchase_currency,
            authorization_token=authorization_token,
            billing_address=billing_address,
            customer=customer,
        )
        return await self._agenerate_customer_token_oapg(
            body=args.body,
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        description: str,
        intended_use: str,
        locale: str,
        purchase_country: str,
        purchase_currency: str,
        authorization_token: str,
        billing_address: typing.Optional[Address] = None,
        customer: typing.Optional[Customer] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._generate_customer_token_mapped_args(
            description=description,
            intended_use=intended_use,
            locale=locale,
            purchase_country=purchase_country,
            purchase_currency=purchase_currency,
            authorization_token=authorization_token,
            billing_address=billing_address,
            customer=customer,
        )
        return self._generate_customer_token_oapg(
            body=args.body,
            path_params=args.path,
        )

