# coding: utf-8

# flake8: noqa

"""
    Klarna Payments API V1

    The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.0.0"

# import ApiClient
from klarna_payments_python_sdk.api_client import ApiClient

# import Configuration
from klarna_payments_python_sdk.configuration import Configuration

# import exceptions
from klarna_payments_python_sdk.exceptions import OpenApiException
from klarna_payments_python_sdk.exceptions import ApiAttributeError
from klarna_payments_python_sdk.exceptions import ApiTypeError
from klarna_payments_python_sdk.exceptions import ApiValueError
from klarna_payments_python_sdk.exceptions import ApiKeyError
from klarna_payments_python_sdk.exceptions import ApiException

from klarna_payments_python_sdk.client import KlarnaPayments
