# coding: utf-8

"""
    Klarna Payments API V1

    The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class AssetUrls(BaseModel):
    # URL of the descriptive asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
    descriptive: typing.Optional[str] = Field(None, alias='descriptive')

    # URL of the standard asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
    standard: typing.Optional[str] = Field(None, alias='standard')
    class Config:
        arbitrary_types_allowed = True
