# coding: utf-8

"""
    Klarna Payments API V1

    The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCustomer(TypedDict):
    pass

class OptionalCustomer(TypedDict, total=False):
    # Customer’s Title. Allowed values per country: UK - \"Mr\", \"Ms\" DE - \"Herr\", \"Frau\" AT: \"Herr, \"Frau\" CH: de-CH: \"Herr, \"Frau\" it-CH: \"Sig.\", \"Sig.ra\" fr-CH: \"M\", \"Mme\"  BE: \"Dhr.\", \"Mevr.\" NL: \"Dhr.\", \"Mevr.\"
    title: str

    # Customer’s date of birth. The format is ‘yyyy-mm-dd’
    date_of_birth: str

    # Customer’s gender - ‘male’ or ‘female’
    gender: str

    # Last four digits of the customer's social security number. This value is available for US customers.
    last_four_ssn: str

    # The customer's national identification number. This value is available for EU customers utilizing national identification numbers.
    national_identification_number: str

    # Organization entity type. Only applicable for B2B customers.
    organization_entity_type: str

    # Organization registration id. Only applicable for B2B customers.
    organization_registration_id: str

    # Type of customer in the session. If nothing is added, a B2C session will be the default. If it is a b2b-session, you should enter organization to trigger a B2B session.
    type: str

    # VAT ID. Only applicable for B2B customers.
    vat_id: str

class Customer(RequiredCustomer, OptionalCustomer):
    pass
