# coding: utf-8

"""
    Klarna Payments API V1

    The payments API is used to create a session to offer Klarna's payment methods as part of your checkout. As soon as the purchase is completed the order should be read and handled using the [`Order Management API`](https://docs.klarna.com/api/ordermanagement).  **Note:** Examples provided in this section includes full payloads, including all supported fields , required and optionals. In order to implement a best in class request we recommend you don't include customer details when initiating a payment session. Refer to [Initiate a payment](https://docs.klarna.com/klarna-payments/integrate-with-klarna-payments/step-1-initiate-a-payment/) section for further details.  Read more on [Klarna payments](https://docs.klarna.com/klarna-payments/).

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from klarna_payments_python_sdk.paths.payments_v1_authorizations_authorization_token.delete import CancelAuthorizationRaw
from klarna_payments_python_sdk.paths.payments_v1_authorizations_authorization_token_order.post import CreateOrderRaw
from klarna_payments_python_sdk.paths.payments_v1_sessions.post import CreateSessionRaw
from klarna_payments_python_sdk.paths.payments_v1_authorizations_authorization_token_customer_token.post import GenerateCustomerTokenRaw
from klarna_payments_python_sdk.paths.payments_v1_sessions_session_id.get import GetSessionDetailsRaw
from klarna_payments_python_sdk.paths.payments_v1_sessions_session_id.post import UpdateSessionDetailsRaw


class PaymentApiRaw(
    CancelAuthorizationRaw,
    CreateOrderRaw,
    CreateSessionRaw,
    GenerateCustomerTokenRaw,
    GetSessionDetailsRaw,
    UpdateSessionDetailsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
